
export const educationItems = [
  {
    id: 1,
    title: "Comprendre les fonds d'urgence",
    description: "Apprenez pourquoi tout le monde a besoin d'un fonds d'urgence et comment en constituer un efficacement.",
    category: "saving",
    type: "article",
    readTime: "5 min de lecture",
    views: 1245,
    image: "https://images.unsplash.com/photo-1579621970588-a35d0e7ab9b6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.lafinancepourtous.com/pratique/vie-perso/epargne-de-precaution/comment-se-constituer-une-epargne-de-precaution/",
  },
  {
    id: 2,
    title: "Budget 101: La règle 50/30/20",
    description: "Un cadre de budgétisation simple que tout le monde peut utiliser pour gérer son argent efficacement.",
    category: "budgeting",
    type: "video",
    readTime: "8 min de visionnage",
    views: 3280,
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    link: "https://www.youtube.com/watch?v=HQzoZfc3GwQ",
  },
  {
    id: 3,
    title: "Introduction à la bourse",
    description: "Les bases de l'investissement en bourse pour les débutants complets, expliquées simplement.",
    category: "investing",
    type: "article",
    readTime: "10 min de lecture",
    views: 4521,
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.amf-france.org/fr/espace-epargnants/comprendre-les-marches-financiers/les-ordres-de-bourse",
  },
  {
    id: 4,
    title: "Comprendre le système fiscal marocain",
    description: "Un guide complet sur les impôts pour les particuliers au Maroc, avec conseils pratiques.",
    category: "taxes",
    type: "article",
    readTime: "12 min de lecture",
    views: 978,
    image: "https://images.unsplash.com/photo-1586486855514-8c633cc6fd38?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.tax.gov.ma/wps/portal/Home/Home",
  },
  {
    id: 5,
    title: "Les meilleures stratégies d'épargne pour 2024",
    description: "Découvrez comment maximiser votre épargne dans le contexte économique actuel avec ces conseils experts.",
    category: "saving",
    type: "video",
    readTime: "15 min de visionnage",
    views: 2150,
    image: "https://images.unsplash.com/photo-1621252179027-95c3e9900d1b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    link: "https://www.youtube.com/watch?v=fVToMS2Q3XQ",
  },
  {
    id: 6,
    title: "Comment investir dans l'immobilier avec un petit budget",
    description: "Les différentes options pour entrer sur le marché immobilier sans gros capital initial.",
    category: "investing",
    type: "article",
    readTime: "8 min de lecture",
    views: 3467,
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.challenges.fr/immobilier/investir-dans-l-immobilier-avec-un-petit-budget-c-est-possible_813843",
  },
  {
    id: 7,
    title: "La psychologie derrière les dépenses impulsives",
    description: "Comprendre les facteurs psychologiques qui influencent nos habitudes de dépense et comment les contrôler.",
    category: "psychology",
    type: "video",
    readTime: "10 min de visionnage",
    views: 1876,
    image: "https://images.unsplash.com/photo-1593672715438-d88a70629abe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    link: "https://www.youtube.com/watch?v=PsihkFWDt3Y",
  },
  {
    id: 8,
    title: "Les bases des ETF: Pour les investisseurs débutants",
    description: "Tout ce que vous devez savoir sur les fonds négociés en bourse et comment commencer à investir.",
    category: "investing",
    type: "article",
    readTime: "7 min de lecture",
    views: 2932,
    image: "https://images.unsplash.com/photo-1569025743873-ea3a9ade89f9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.boursorama.com/bourse/trackers/etf/",
  },
  {
    id: 9,
    title: "Comment établir un budget familial efficace",
    description: "Stratégies pratiques pour gérer les finances d'un ménage avec enfants et maximiser vos économies.",
    category: "budgeting",
    type: "video",
    readTime: "12 min de visionnage",
    views: 4120,
    image: "https://images.unsplash.com/photo-1590073242678-70ee3fc28f17?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2304&q=80",
    link: "https://www.youtube.com/watch?v=bpNx7xKHGZ0",
  },
  {
    id: 10,
    title: "Les biais cognitifs qui affectent vos décisions financières",
    description: "Identifier et surmonter les préjugés mentaux qui peuvent nuire à votre santé financière à long terme.",
    category: "psychology",
    type: "article",
    readTime: "9 min de lecture",
    views: 1543,
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.lemonde.fr/argent/article/2020/09/11/placements-attention-aux-biais-cognitifs_6051772_1657007.html",
  },
  {
    id: 11,
    title: "Optimisation fiscale légale pour particuliers",
    description: "Comment réduire légalement votre impôt sur le revenu grâce à différents dispositifs au Maroc.",
    category: "taxes",
    type: "video",
    readTime: "14 min de visionnage",
    views: 2670,
    image: "https://images.unsplash.com/photo-1554224155-1696413565d3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    link: "https://www.youtube.com/watch?v=OvAEQhbuvMI",
  },
  {
    id: 12,
    title: "Guide des placements pour jeunes professionnels",
    description: "Les meilleures options d'investissement quand on débute sa carrière et comment les maximiser.",
    category: "investing",
    type: "article",
    readTime: "11 min de lecture",
    views: 3290,
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.lesechos.fr/finance-marches/banque-assurances/placements-comment-faire-les-bons-choix-quand-on-est-jeune-1146630",
  },
  {
    id: 13,
    title: "Gérer efficacement son endettement",
    description: "Stratégies pour réduire vos dettes et retrouver une liberté financière plus rapidement.",
    category: "debt",
    type: "article",
    readTime: "8 min de lecture",
    views: 2754,
    image: "https://images.unsplash.com/photo-1434626881859-194d67b2b86f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.economie.gouv.fr/particuliers/surendettement",
  },
  {
    id: 14,
    title: "Préparer sa retraite dès 30 ans",
    description: "Pourquoi et comment commencer à planifier sa retraite tôt pour maximiser ses revenus futurs.",
    category: "retirement",
    type: "video",
    readTime: "16 min de visionnage",
    views: 1865,
    image: "https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    link: "https://www.youtube.com/watch?v=Ir3VAfQyiO4",
  },
  {
    id: 15,
    title: "Comment négocier son salaire efficacement",
    description: "Techniques éprouvées pour négocier une augmentation ou un meilleur salaire à l'embauche.",
    category: "psychology",
    type: "article",
    readTime: "7 min de lecture",
    views: 4310,
    image: "https://images.unsplash.com/photo-1574622635855-f25c891a188d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.cadremploi.fr/editorial/conseils/conseils-carriere/comment-negocier-son-salaire-a-l-embauche",
  },
  {
    id: 16,
    title: "L'investissement socialement responsable",
    description: "Comment investir selon vos valeurs tout en assurant un bon rendement financier.",
    category: "investing",
    type: "video",
    readTime: "13 min de visionnage",
    views: 1540,
    image: "https://images.unsplash.com/photo-1536859355448-76f92ebdc33d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    link: "https://www.youtube.com/watch?v=weVAN2HxXjk",
  },
  {
    id: 17,
    title: "Impôts: Déclaration en ligne au Maroc",
    description: "Guide étape par étape pour remplir votre déclaration d'impôts en ligne facilement.",
    category: "taxes",
    type: "article",
    readTime: "6 min de lecture",
    views: 5230,
    image: "https://images.unsplash.com/photo-1563906267088-b029e7101114?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.tax.gov.ma/wps/portal/Home/Home",
  },
  {
    id: 18,
    title: "Méthode d'épargne automatique",
    description: "Comment mettre en place un système d'épargne automatique efficace pour atteindre vos objectifs.",
    category: "saving",
    type: "video",
    readTime: "9 min de visionnage",
    views: 2860,
    image: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    link: "https://www.youtube.com/watch?v=kHR4bYfP-XE",
  },
  {
    id: 19,
    title: "Crypto-monnaies: Guide du débutant",
    description: "Comprendre les bases des crypto-monnaies et comment investir de façon sécurisée.",
    category: "investing",
    type: "article",
    readTime: "14 min de lecture",
    views: 6250,
    image: "https://images.unsplash.com/photo-1625466210039-926f3889bf93?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    source: "https://www.cnil.fr/fr/cryptomonnaies-cryptoactifs-comprendre-et-proteger-ses-donnees",
  },
  {
    id: 20,
    title: "Apprendre aux enfants la valeur de l'argent",
    description: "Conseils pratiques pour éduquer vos enfants à la gestion financière dès le plus jeune âge.",
    category: "psychology",
    type: "video",
    readTime: "11 min de visionnage",
    views: 3175,
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    link: "https://www.youtube.com/watch?v=djJAVZSN4P4",
  },
];
